name:                day18
version:             0.1.0.0
license:             BSD3
author:              "PhiliPdB"
copyright:           "2021 PhiliPdB"

dependencies:
- base >= 4.7 && < 5
- uu-tc

executables:
  day18:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
